@val external rpc: string = "RPC_URL"
@val external grpc: string = "GRPC"
@val external graphql: string = "GRAPHQL_URL"
@val external lambda: string = "LAMBDA_URL"
@val external faucet: string = "FAUCET_URL"
